import { CustomStatusBar } from '@/components/ui/custom-status-bar';
import { SettingsHeader } from '@/components/ui/settings-header';
import { colors } from '@/constants/colors';
import { useWalletStore } from '@/store/walletStore';
import Ionicons from '@expo/vector-icons/Ionicons';
import * as Clipboard from 'expo-clipboard';
import { Image } from 'expo-image';
import { useRouter } from 'expo-router';
import React, { useState } from 'react';
import { Alert, ScrollView, Share, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

// Assets from Figma
const imgFrameReferral = require('../../assets/home/frame-referral.png');
const imgCopy01 = require('../../assets/referral/copy-01.svg');
const imgShare01 = require('../../assets/referral/share-01.svg');

// Mock leaderboard data
const leaderboardData = [
    { level: 1, volumeRange: '<$100,5000', rebateShare: '30%', color: '#B1F128' },
    { level: 2, volumeRange: '>$100,000', rebateShare: '35%', color: '#B1F128' },
    { level: 3, volumeRange: '>$5,000,0000', rebateShare: '40%', color: '#B1F128' },
    { level: 4, volumeRange: '>$10,000,0000', rebateShare: '45%', color: '#B1F128' },
    { level: 5, volumeRange: '>$12,500,0000', rebateShare: '50%', color: '#B1F128' },
    { level: 6, volumeRange: '>$20,500,0000', rebateShare: '60%', color: '#B1F128' },
];

const faqs = [
    {
        question: 'What is the referral rebate',
        answer: 'The referral rebate is a percentage of the trading fees generated by users you refer to TIWI Protocol.'
    },
    {
        question: 'How is my rebate calculated',
        answer: 'Your rebate is calculated based on your referral level and the trading volume of your referees.'
    },
    {
        question: 'When can I claim my rebate',
        answer: 'Claims open every 28th of the month. You can claim your accumulated USDT rewards directly to your wallet.'
    },
    {
        question: 'Can I change my referrer',
        answer: 'No, once you sign up with a referral code, that referrer relationship is permanent.'
    },
];

/**
 * Referral Position/Leaderboard Screen
 * Shows detailed referral stats, leaderboard, and FAQs
 * Exact implementation from Figma design (node-id: 3279-116844)
 */
export default function ReferralPositionScreen() {
    const router = useRouter();
    const { bottom } = useSafeAreaInsets();
    const { address } = useWalletStore();

    const [expandedFaq, setExpandedFaq] = useState<number | null>(null);

    // Mock data - replace with actual API calls
    const recentEarnings = '20.61 USDT';
    const recentReferrer = '0x09...879';
    const totalInvites = 0;
    const claimableRewards = '$0.00';
    const totalBonuses = '0.0000';
    const referralCode = 'TIWI01034';
    const referralLink = 'https://www.tiwipro...';
    const currentLevel = 1;
    const spotRebate = '30%';
    const perpRebate = 'My Perp Rebate';

    const handleCopyCode = async () => {
        await Clipboard.setStringAsync(referralCode);
        Alert.alert('Copied', 'Referral code copied to clipboard!');
    };

    const handleCopyLink = async () => {
        await Clipboard.setStringAsync(referralLink);
        Alert.alert('Copied', 'Referral link copied to clipboard!');
    };

    const handleShare = async () => {
        try {
            await Share.share({
                message: `Join me on TIWI Protocol! Use my code ${referralCode} to get started: ${referralLink}`,
                url: referralLink,
            });
        } catch (error) {
            console.log('Error sharing', error);
        }
    };

    const handleInviteFriend = () => {
        handleShare();
    };

    const toggleFaq = (index: number) => {
        setExpandedFaq(expandedFaq === index ? null : index);
    };

    return (
        <View style={styles.container}>
            <CustomStatusBar />
            <SettingsHeader
                title="Referrals"
                onBack={() => router.back()}
                showBack={true}
            />

            <ScrollView
                style={styles.scrollView}
                contentContainerStyle={[styles.content, { paddingBottom: bottom + 100 }]}
                showsVerticalScrollIndicator={false}
            >
                {/* Hero Card */}
                <View style={styles.heroCard}>
                    <View style={styles.heroTextContainer}>
                        <Text style={styles.heroTitle}>
                            Invite Friends,{'\n'}Unlock{'\n'}Rewards.
                        </Text>
                    </View>
                    <Image
                        source={imgFrameReferral}
                        style={styles.heroImage}
                        contentFit="contain"
                    />
                </View>

                {/* Recent Earnings Banner */}
                <View style={styles.earningsBanner}>
                    <View style={styles.earningsLeft}>
                        <Text style={styles.earningsLabel}>
                            {recentReferrer} has recently invited ...
                        </Text>
                        <Text style={styles.earningsAmount}>{recentEarnings}</Text>
                    </View>
                    <TouchableOpacity style={styles.positionButton} activeOpacity={0.7}>
                        <Text style={styles.positionText}>Position</Text>
                        <Ionicons name="arrow-forward" size={16} color={colors.titleText} />
                    </TouchableOpacity>
                </View>

                {/* How To Invite Section */}
                <View style={styles.howToSection}>
                    <Text style={styles.sectionTitle}>How To Invite</Text>
                    <View style={styles.howToGrid}>
                        <View style={styles.howToItem}>
                            <View style={styles.howToIconWrapper}>
                                <Image source={imgShare01} style={styles.howToIcon} contentFit="contain" />
                            </View>
                            <Text style={styles.howToLabel}>Share Your{'\n'}Link</Text>
                        </View>
                        <View style={styles.howToItem}>
                            <View style={styles.howToIconWrapper}>
                                <Ionicons name="person-add" size={24} color={colors.primaryCTA} />
                            </View>
                            <Text style={styles.howToLabel}>Friend{'\n'}Signs Up</Text>
                        </View>
                        <View style={styles.howToItem}>
                            <View style={styles.howToIconWrapper}>
                                <Ionicons name="cash" size={24} color={colors.primaryCTA} />
                            </View>
                            <Text style={styles.howToLabel}>Earn{'\n'}Together</Text>
                        </View>
                    </View>
                </View>

                {/* My Referrals Section */}
                <View style={styles.myReferralsSection}>
                    <Text style={styles.sectionTitle}>My Referrals</Text>
                    <View style={styles.statsGrid}>
                        <View style={styles.statCard}>
                            <Text style={styles.statLabel}>Total Invites</Text>
                            <Text style={styles.statValue}>{totalInvites}</Text>
                        </View>
                        <View style={styles.statCard}>
                            <Text style={styles.statLabel}>Claimable Rewards</Text>
                            <Text style={styles.statValue}>{claimableRewards}</Text>
                        </View>
                    </View>
                    <View style={styles.bonusCard}>
                        <Text style={styles.bonusLabel}>Total Bonuses (USDT)</Text>
                        <Text style={styles.bonusValue}>{totalBonuses}</Text>
                        <TouchableOpacity style={styles.claimButton} activeOpacity={0.8}>
                            <Text style={styles.claimButtonText}>Claim</Text>
                        </TouchableOpacity>
                    </View>
                </View>

                {/* Referral Code & Link */}
                <View style={styles.codeSection}>
                    <View style={styles.codeRow}>
                        <Text style={styles.codeLabel}>My Referral Code</Text>
                        <View style={styles.codeValueRow}>
                            <Text style={styles.codeValue}>{referralCode}</Text>
                            <TouchableOpacity onPress={handleCopyCode} style={styles.copyIconButton}>
                                <Image source={imgCopy01} style={styles.copyIcon} contentFit="contain" />
                            </TouchableOpacity>
                        </View>
                    </View>
                    <View style={styles.codeRow}>
                        <Text style={styles.codeLabel}>My Referral Link</Text>
                        <View style={styles.codeValueRow}>
                            <Text style={styles.codeValue} numberOfLines={1}>{referralLink}</Text>
                            <TouchableOpacity onPress={handleCopyLink} style={styles.copyIconButton}>
                                <Image source={imgCopy01} style={styles.copyIcon} contentFit="contain" />
                            </TouchableOpacity>
                        </View>
                    </View>
                </View>

                {/* Referral Leaderboard */}
                <View style={styles.leaderboardSection}>
                    <View style={styles.leaderboardHeader}>
                        <Text style={styles.sectionTitle}>Referral Leaderboard</Text>
                        <Text style={styles.sectionTitle}>Rebate Level</Text>
                    </View>

                    <View style={styles.currentLevelCard}>
                        <Text style={styles.currentLevelLabel}>My Rebate Level: {currentLevel}</Text>
                    </View>

                    <View style={styles.rebateGrid}>
                        <View style={styles.rebateCard}>
                            <Text style={styles.rebateLabel}>Invited Frens</Text>
                            <Text style={styles.rebateValue}>Frens' Spot Vol</Text>
                            <Text style={styles.rebateValue}>Frens' Perp Vol</Text>
                        </View>
                        <View style={styles.rebateCard}>
                            <Text style={styles.rebateLabel}>My Spot Rebate</Text>
                            <Text style={styles.rebateValue}>{spotRebate}</Text>
                        </View>
                        <View style={styles.rebateCard}>
                            <Text style={styles.rebateLabel}>{perpRebate}</Text>
                        </View>
                    </View>

                    {/* Leaderboard Table */}
                    <View style={styles.leaderboardTable}>
                        <View style={styles.tableHeader}>
                            <Text style={styles.tableHeaderText}>Level</Text>
                            <Text style={styles.tableHeaderText}>28 day referee{'\n'}spot/perp vol</Text>
                            <Text style={styles.tableHeaderText}>Rebate share{'\n'}adjusted to{'\n'}0.25% fee</Text>
                        </View>
                        {leaderboardData.map((item, index) => (
                            <View
                                key={index}
                                style={[
                                    styles.tableRow,
                                    item.level === currentLevel && styles.tableRowActive
                                ]}
                            >
                                <View style={styles.levelCell}>
                                    {item.level === currentLevel && (
                                        <View style={styles.levelDot} />
                                    )}
                                    <Text style={styles.tableCellText}>Level {item.level}</Text>
                                </View>
                                <Text style={styles.tableCellText}>{item.volumeRange}</Text>
                                <Text style={[styles.tableCellText, styles.rebateText]}>{item.rebateShare}</Text>
                            </View>
                        ))}
                    </View>
                </View>

                {/* FAQs Section */}
                <View style={styles.faqSection}>
                    <Text style={styles.sectionTitle}>Frequently Asked Questions (FAQs)</Text>
                    {faqs.map((faq, index) => (
                        <TouchableOpacity
                            key={index}
                            style={styles.faqItem}
                            onPress={() => toggleFaq(index)}
                            activeOpacity={0.8}
                        >
                            <View style={styles.faqHeader}>
                                <Text style={styles.faqQuestion}>{faq.question}</Text>
                                <Ionicons
                                    name={expandedFaq === index ? "chevron-up" : "chevron-down"}
                                    size={20}
                                    color={colors.titleText}
                                />
                            </View>
                            {expandedFaq === index && (
                                <Text style={styles.faqAnswer}>{faq.answer}</Text>
                            )}
                        </TouchableOpacity>
                    ))}
                </View>

            </ScrollView>

            {/* Fixed Bottom Button */}
            <View style={[styles.bottomButtonContainer, { paddingBottom: bottom + 16 }]}>
                <TouchableOpacity
                    style={styles.inviteButton}
                    onPress={handleInviteFriend}
                    activeOpacity={0.8}
                >
                    <Ionicons name="person-add" size={20} color="#000" />
                    <Text style={styles.inviteButtonText}>Invite Friend</Text>
                </TouchableOpacity>
                <TouchableOpacity style={styles.qrButton} activeOpacity={0.8}>
                    <Ionicons name="qr-code" size={24} color={colors.titleText} />
                </TouchableOpacity>
            </View>
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.bg,
    },
    scrollView: {
        flex: 1,
    },
    content: {
        paddingHorizontal: 16,
        paddingTop: 16,
    },
    heroCard: {
        width: '100%',
        height: 120,
        backgroundColor: colors.primaryCTA,
        borderRadius: 16,
        marginBottom: 16,
        overflow: 'hidden',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingLeft: 24,
    },
    heroTextContainer: {
        flex: 1,
    },
    heroTitle: {
        fontFamily: 'Manrope-Bold',
        fontSize: 24,
        lineHeight: 32,
        color: '#000000',
        letterSpacing: -0.5,
    },
    heroImage: {
        width: 160,
        height: 120,
        position: 'absolute',
        right: 0,
        top: 0,
    },
    earningsBanner: {
        width: '100%',
        backgroundColor: colors.bgCards,
        borderRadius: 12,
        padding: 16,
        marginBottom: 24,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderWidth: 1,
        borderColor: colors.bgStroke,
    },
    earningsLeft: {
        flex: 1,
    },
    earningsLabel: {
        fontFamily: 'Manrope-Medium',
        fontSize: 12,
        color: colors.mutedText,
        marginBottom: 4,
    },
    earningsAmount: {
        fontFamily: 'Manrope-Bold',
        fontSize: 16,
        color: colors.primaryCTA,
    },
    positionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    positionText: {
        fontFamily: 'Manrope-Medium',
        fontSize: 14,
        color: colors.titleText,
    },
    sectionTitle: {
        fontFamily: 'Manrope-Bold',
        fontSize: 16,
        color: colors.titleText,
        marginBottom: 16,
    },
    howToSection: {
        marginBottom: 24,
    },
    howToGrid: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
    },
    howToItem: {
        flex: 1,
        alignItems: 'center',
        gap: 12,
    },
    howToIconWrapper: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: colors.bgCards,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: colors.bgStroke,
    },
    howToIcon: {
        width: 24,
        height: 24,
    },
    howToLabel: {
        fontFamily: 'Manrope-Medium',
        fontSize: 12,
        color: colors.titleText,
        textAlign: 'center',
        lineHeight: 16,
    },
    myReferralsSection: {
        marginBottom: 24,
    },
    statsGrid: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 12,
    },
    statCard: {
        flex: 1,
        backgroundColor: colors.bgCards,
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: colors.bgStroke,
    },
    statLabel: {
        fontFamily: 'Manrope-Medium',
        fontSize: 12,
        color: colors.mutedText,
        marginBottom: 8,
    },
    statValue: {
        fontFamily: 'Manrope-Bold',
        fontSize: 18,
        color: colors.titleText,
    },
    bonusCard: {
        backgroundColor: colors.bgCards,
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: colors.bgStroke,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    bonusLabel: {
        fontFamily: 'Manrope-Medium',
        fontSize: 12,
        color: colors.mutedText,
        flex: 1,
    },
    bonusValue: {
        fontFamily: 'Manrope-Bold',
        fontSize: 16,
        color: colors.titleText,
        marginRight: 12,
    },
    claimButton: {
        backgroundColor: colors.primaryCTA,
        borderRadius: 8,
        paddingHorizontal: 20,
        paddingVertical: 8,
    },
    claimButtonText: {
        fontFamily: 'Manrope-Bold',
        fontSize: 14,
        color: '#000000',
    },
    codeSection: {
        marginBottom: 24,
        gap: 12,
    },
    codeRow: {
        backgroundColor: colors.bgCards,
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: colors.bgStroke,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    codeLabel: {
        fontFamily: 'Manrope-Medium',
        fontSize: 14,
        color: colors.bodyText,
        flex: 1,
    },
    codeValueRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        flex: 1,
        justifyContent: 'flex-end',
    },
    codeValue: {
        fontFamily: 'Manrope-Bold',
        fontSize: 14,
        color: colors.titleText,
    },
    copyIconButton: {
        padding: 4,
    },
    copyIcon: {
        width: 16,
        height: 16,
    },
    leaderboardSection: {
        marginBottom: 24,
    },
    leaderboardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    currentLevelCard: {
        backgroundColor: colors.bgCards,
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: colors.bgStroke,
    },
    currentLevelLabel: {
        fontFamily: 'Manrope-Bold',
        fontSize: 14,
        color: colors.titleText,
    },
    rebateGrid: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 16,
    },
    rebateCard: {
        flex: 1,
        backgroundColor: colors.bgCards,
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: colors.bgStroke,
        gap: 8,
    },
    rebateLabel: {
        fontFamily: 'Manrope-Medium',
        fontSize: 11,
        color: colors.mutedText,
    },
    rebateValue: {
        fontFamily: 'Manrope-Bold',
        fontSize: 12,
        color: colors.titleText,
    },
    leaderboardTable: {
        backgroundColor: colors.bgCards,
        borderRadius: 12,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: colors.bgStroke,
    },
    tableHeader: {
        flexDirection: 'row',
        backgroundColor: '#0D3600',
        padding: 12,
        borderBottomWidth: 1,
        borderBottomColor: colors.bgStroke,
    },
    tableHeaderText: {
        flex: 1,
        fontFamily: 'Manrope-Bold',
        fontSize: 11,
        color: colors.titleText,
        textAlign: 'center',
    },
    tableRow: {
        flexDirection: 'row',
        padding: 12,
        borderBottomWidth: 1,
        borderBottomColor: colors.bgStroke,
        alignItems: 'center',
    },
    tableRowActive: {
        backgroundColor: 'rgba(177, 241, 40, 0.05)',
    },
    levelCell: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    levelDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: colors.primaryCTA,
    },
    tableCellText: {
        flex: 1,
        fontFamily: 'Manrope-Medium',
        fontSize: 12,
        color: colors.bodyText,
        textAlign: 'center',
    },
    rebateText: {
        color: colors.primaryCTA,
        fontFamily: 'Manrope-Bold',
    },
    faqSection: {
        marginBottom: 24,
    },
    faqItem: {
        backgroundColor: colors.bgCards,
        borderRadius: 12,
        padding: 20,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: colors.bgStroke,
    },
    faqHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    faqQuestion: {
        flex: 1,
        fontFamily: 'Manrope-SemiBold',
        fontSize: 14,
        color: colors.titleText,
    },
    faqAnswer: {
        fontFamily: 'Manrope-Medium',
        fontSize: 13,
        color: colors.bodyText,
        marginTop: 12,
        lineHeight: 20,
    },
    bottomButtonContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        paddingHorizontal: 16,
        paddingTop: 16,
        backgroundColor: colors.bg,
        borderTopWidth: 1,
        borderTopColor: colors.bgStroke,
        flexDirection: 'row',
        gap: 12,
    },
    inviteButton: {
        flex: 1,
        height: 56,
        backgroundColor: colors.primaryCTA,
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    inviteButtonText: {
        fontFamily: 'Manrope-Bold',
        fontSize: 16,
        color: '#000000',
    },
    qrButton: {
        width: 56,
        height: 56,
        backgroundColor: colors.bgCards,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: colors.bgStroke,
    },
});
