const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Copies every file in `android-assets/` into the APK's `assets/` folder.
 *
 * `android/` is gitignored and regenerated by prebuild on every EAS build, so
 * anything written there by hand is wiped before the build runs. This plugin
 * re-copies the files during the prebuild step instead.
 *
 * Currently this carries `adi-registration.properties`, the token file Google
 * Play requires inside a signed APK to verify ownership of the package name
 * (Play Console > Android developer verification > Manage package keys).
 */
const withAndroidRawAssets = (config) => {
  return withDangerousMod(config, [
    'android',
    async (config) => {
      const srcDir = path.join(config.modRequest.projectRoot, 'android-assets');
      if (!fs.existsSync(srcDir)) return config;

      const destDir = path.join(
        config.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'assets'
      );
      fs.mkdirSync(destDir, { recursive: true });

      for (const name of fs.readdirSync(srcDir)) {
        const from = path.join(srcDir, name);
        if (!fs.statSync(from).isFile()) continue;
        fs.copyFileSync(from, path.join(destDir, name));
        console.log(`[withAndroidRawAssets] copied ${name} -> app/src/main/assets/`);
      }

      return config;
    },
  ]);
};

module.exports = withAndroidRawAssets;
